### ISSUE TITLE
BadTokenException on WindowManager during authentication

### ISSUE THREAD

**Issue by ryandt** [kaaes/spotify-web-api-android#42]
The following exception is thrown after selecting anywhere outside of the loading dialog that is displayed during Spotify authentication. Doing this dismisses the loading dialog and eventually crashes the app when the response is returned, carrying a response type of "empty".

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@4324c420 is not valid; is your activity running?
            at android.view.ViewRootImpl.setView(ViewRootImpl.java:576)
            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
            at android.app.Dialog.show(Dialog.java:292)
            at com.spotify.sdk.android.authentication.LoginDialog$2.onPageStarted(LoginDialog.java:144)
            at com.android.webview.chromium.WebViewContentsClientAdapter.onPageStarted(WebViewContentsClientAdapter.java:444)
            at com.android.org.chromium.android_webview.AwContentsClientCallbackHelper$MyHandler.handleMessage(AwContentsClientCallbackHelper.java:104)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5097)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)
```

This appears to be a window leak issue with the LoginActivity at quick glance, but I'm short on time to step through the stack trace tonight. I'll look at this closer this weekend and post back any updates unless someone else with more visibility into the Spotify Android Authentication code beats me to it.

**Comment by kaaes** [comment]
Yes, I saw it happening and the fix for it will be a part of the next release of Spotify SDK.
Just to verify - how are you getting this error? Is it by tapping on the area outside the dialog?

**Comment by ryandt** [comment]
@kaaes, yes. My MainActivity is visible behind the modal dialog. When selecting anywhere where on the MainActivity view in the background, the loading dialog dismisses, and the app soon after crashes.

**Comment by kaaes** [comment]
I'll opened this issue in Spotify Android SDK and will close it here.
